# Generated by Django 3.2.6 on 2021-08-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='names',
            new_name='name',
        ),
    ]
